/* bib_code_points values */
INSERT INTO
    pr_vigienature.bib_nomenclature_type(code, libelle)
    VALUES
        ('DISTANCE', 'Distances d''observations')
      , ('HAB_ENV', 'Habitats (Milieu, niveau 0)')
      , ('HAB_TYP', 'Habitats (Type, niveau 1)')
      , ('HAB_CAT1', 'Habitats (Catégorie et Sous-Cat 1, niveau 2)')
      , ('HAB_CAT2', 'Habitats (Catégorie et Sous-Cat 2, niveau 3)')
      , ('RAIN', 'Pluie')
      , ('WIND', 'Vent')
      , ('VISIBILITY', 'Visibilité')
      , ('CLOUD', 'Couverture nuageuse')
;

TRUNCATE pr_vigienature.t_nomenclature RESTART IDENTITY CASCADE
;

INSERT INTO
    pr_vigienature.t_nomenclature(type_id, code, code_vn, libelle)
    VALUES
        (pr_vigienature.fct_get_nomenclature_type('HAB_ENV'), 'A', 'A0_A', 'Forêt - Arbres > 5m de haut')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_ENV'), 'B', 'B0_B', 'Buissons/jeune forêt < 5m')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_ENV'), 'C', 'C0_C', 'Pelouses, marais et landes')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_ENV'), 'D', 'D0_D', 'Milieux agricoles')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_ENV'), 'E', 'E0_E', 'Milieux bâtis ou urbanisés')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_ENV'), 'F', 'F0_F', 'Milieux aquatiques')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_ENV'), 'G', 'G0_G', 'Rochers terrestres ou côtiers')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '1', 'A1_1', 'Feuillus')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '2', 'A1_2', 'Conifères')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '3', 'A1_3', 'Mixte (> 10% de chaque)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '1', 'B1_1', 'Forêt de régénération')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '2', 'B1_2', 'Buissons calcicoles')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '3', 'B1_3', 'Lande')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '4', 'B1_4', 'Jeune taillis')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '5', 'B1_5', 'Nouvelle plantation')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '6', 'B1_6', 'Coupe « à blanc »')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '7', 'B1_7', 'Autres')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '1', 'C1_1', 'Pelouse calcaire sèche')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '2', 'C1_2', 'Lande herbacée')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '3', 'C1_3', 'Lande de bruyère')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '4', 'C1_4', 'Pelouse humide naturelle')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '5', 'C1_5', 'Autres pelouses sèches (mur, fossé)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '6', 'C1_6', 'Pelouse inondée/marais pâturé')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '7', 'C1_7', 'Roselière')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '8', 'C1_8', 'Autres marais ouverts')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '9', 'C1_9', 'Marais salants')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '10', 'C1_10', 'Tourbières')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '11', 'C1_11', 'Marais salé')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '1', 'D1_1', 'Prairie cultivée')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '2', 'D1_2', 'Prairie non cultivée')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '3', 'D1_3', 'Mixité prairie / cultures')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '4', 'D1_4', 'Grandes cultures')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '5', 'D1_5', 'Verger / vignes / maraîchers (mur, fossé)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '6', 'D1_6', 'Autres types de cultures')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '1', 'E1_1', 'Urbain')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '2', 'E1_2', 'Suburbain')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '3', 'E1_3', 'Rural')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '1', 'F1_1', 'Mare (moins de 50 m2)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '2', 'F1_2', 'Petit étang (50 - 450 m2)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '3', 'F1_3', 'Lac/réservoir (berges naturelles) ')
      , ( pr_vigienature.fct_get_nomenclature_type('HAB_TYP')
        , '3'
        , 'F2_3'
        , 'Pêche à la ligne (eau claire, peu d’algues)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '4', 'F1_4', 'Réservoir (berges non naturelles)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '5', 'F1_5', 'Carrière de gravier, de sable')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '6', 'F1_6', 'Ruisseau - Larg. < 3m')
      , ( pr_vigienature.fct_get_nomenclature_type('HAB_TYP')
        , '6'
        , 'F2_6'
        , 'Autres dérangements (eau claire, bcp d’algues)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '7', 'F1_7', 'Rivière - Larg. 3 à 10m')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '8', 'F1_8', 'Fossé inondé - Larg. < 2m')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '9', 'F1_9', 'Petit canal –Larg. 2 à 5m')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '10', 'F1_10', 'Grand canal - Larg. > 5m')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '11', 'F1_11', 'Eaux saumâtres salins, lagunes')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '12', 'F1_12', 'Fleuve, rivière Larg. > 10m ')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '13', 'F1_13', 'Rives avec falaise')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '1', 'G1_1', 'Falaise')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '2', 'G1_2', 'Eboulis, pente rocheuse')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '3', 'G1_3', 'Pavement calcaire')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '4', 'G1_4', 'Autres sols rocheux')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '5', 'G1_5', 'Carrière (grimpeurs, promeneurs) ')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '6', 'G1_6', 'Mine / abîme / terril')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '7', 'G1_7', 'Grotte')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_TYP'), '8', 'G1_8', 'Dune')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '1', 'A2_1', 'Semi-naturelle ou âges mélangés')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '2', 'A2_2', 'Plantation équienne')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '3', 'A2_3', 'Plantation non-équienne')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '4', 'A2_4', 'Plantation mâture (> 10m)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '5', 'A2_5', 'Jeune plantation (5-10m)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '6', 'A2_6', 'Parc (arbres épars et prairies)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '7', 'A2_7', 'Sous-bois dense')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '8', 'A2_8', 'Sous-bois modéré')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '9', 'A2_9', 'Sous-bois épars')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '10', 'A2_10', 'Bois mort présent')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '11', 'A2_11', 'Bois mort absent')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '1', 'B2_1', 'Feuillus')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '2', 'B2_2', 'Conifères')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '3', 'B2_3', 'Mixte (10% de chaque)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '4', 'B2_4', 'Buissons feuillus de marais')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '5', 'B2_5', 'Buissons conifères de marais')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '6', 'B2_6', 'Buissons mixtes de marais')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '7', 'B2_7', 'Feuilles persistantes')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '8', 'B2_8', 'Garrigue')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '9', 'B2_9', 'Maquis')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '1', 'C2_1', 'Haies avec arbres')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '2', 'C2_2', 'Haies sans arbres')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '3', 'C2_3', 'Lignes d’arbres sans haie')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '4', 'C2_4', 'Autre limite de terrain')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '5', 'C2_5', 'Groupe isolé de 1-10 arbres')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '6', 'C2_6', 'Pas de haie')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '7', 'C2_7', 'Montagne')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '8', 'C2_8', 'Digue')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '1', 'D2_1', 'Haies avec arbres')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '2', 'D2_2', 'Haies sans arbres')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '3', 'D2_3', 'Ligne d’arbres sans haie')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '4', 'D2_4', 'Autre limite de terrain')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '5', 'D2_5', 'Groupes isolés de 1-10 arbres')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '6', 'D2_6', 'Cour de ferme, basse-cour')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '7', 'D2_7', 'Pas de haie')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '1', 'E2_1', 'Bâtiments')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '2', 'E2_2', 'Jardins')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '3', 'E2_3', 'Parcs municipaux, zones de loisirs')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '4', 'E2_4', 'Traitement des eaux urbaines')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '5', 'E2_5', 'Près d’une route (< 50m)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '6', 'E2_6', 'Près d’une voie ferrée (< 50m)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '7', 'E2_7', 'Décharge d’ordures')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '8', 'E2_8', 'Beaucoup de buissons')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '9', 'E2_9', 'Peu de buissons')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '1', 'F2_1', 'Non utilisé/non perturbé')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '2', 'F2_2', 'Sports nautiques')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '3', 'F3_3', 'Dystrophique (eau noire)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '4', 'F2_4', 'Activité industrielle')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '5', 'F2_5', 'Traitements d’eaux usées')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '6', 'F3_6', 'Courant fort')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '7', 'F2_7', 'Activité industrielle')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '8', 'F2_8', 'Petites îles')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '1', 'G2_1', 'Montagne')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '2', 'G2_2', 'Pas en montagne')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '3', 'G2_3', 'Bord de mer (mousses, lichens)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT1'), '4', 'G2_4', 'Fort dérangement par l’homme')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '1', 'A3_1', 'Chêne')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '2', 'A3_2', 'Hêtre')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '3', 'A3_3', 'Erable')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '4', 'A3_4', 'Châtaignier')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '5', 'A3_5', 'Autre essence feuillue')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '6', 'A3_6', 'Sapin')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '7', 'A3_7', 'Epicéa')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '8', 'A3_8', 'Pin')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '9', 'A3_9', 'Mélèze')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '10', 'A3_10', 'Autre essence conifère')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '11', 'A3_11', 'Autre essence')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '1', 'B3_1', 'Surtout grands (3-5m)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '2', 'B3_2', 'Surtout petits (1-3m)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '3', 'B3_3', 'Sous-bois dense')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '4', 'B3_4', 'Sous-bois modéré')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '5', 'B3_5', 'Sous-bois éparse')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '6', 'B3_6', 'Fougères')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '7', 'B3_7', 'Pâturé')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '1', 'C3_1', 'Non pâturé')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '2', 'C3_2', 'Pâturé')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '3', 'C3_3', 'Foin')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '4', 'C3_4', 'Beaucoup de fougères')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '1', 'D3_1', 'Non pâturé')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '2', 'D3_2', 'Pâturé')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '3', 'D3_3', 'Céréales')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '4', 'D3_4', 'Maïs')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '5', 'D3_5', 'Tournesol')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '6', 'D3_6', 'Colza')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '7', 'D3_7', 'Cultures à racines')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '8', 'D3_8', 'Sol nu')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '9', 'D3_9', 'Autres cultures')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '10', 'D3_10', 'Rizières')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '1', 'E3_1', 'Industriel')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '2', 'E3_2', 'Résidentiel')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '3', 'E3_3', 'Beaucoup d’arbres')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '4', 'E3_4', 'Peu d’arbres')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '5', 'E3_5', 'Grande surface de jardins (> 450m2)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '6', 'E3_6', 'Moyenne surface de jardins (100 - 450 m2)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '7', 'E3_7', 'Faible surface de jardins (< 100 m2)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '1', 'F3_1', 'Eutrophique (eau verte)')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '2', 'F3_2', 'Oligotrophique')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '4', 'F3_4', 'Bigarré')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '5', 'F3_5', 'Courant faible / moyen')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '7', 'F3_7', 'Dragué')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '8', 'F3_8', 'Non dragué')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '9', 'F3_9', 'Rives nues')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '10', 'F3_10', 'Rives avec végétation')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '1', 'G3_1', 'Roche nue')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '2', 'G3_2', 'Végétation basse présente')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '3', 'G3_3', 'Graminées présentes')
      , (pr_vigienature.fct_get_nomenclature_type('HAB_CAT2'), '4', 'G3_4', 'Buissons présents')
      , (pr_vigienature.fct_get_nomenclature_type('DISTANCE'), 'D', 'LESS25', '< 25m')
      , (pr_vigienature.fct_get_nomenclature_type('DISTANCE'), 'V', 'TRANSIT', 'En vol')
      , (pr_vigienature.fct_get_nomenclature_type('DISTANCE'), 'L', 'LESS200', '100-200m')
      , (pr_vigienature.fct_get_nomenclature_type('DISTANCE'), 'M', 'MORE200', '> 200m')
      , (pr_vigienature.fct_get_nomenclature_type('DISTANCE'), 'F', 'LESS100', '25-100m')
      , (pr_vigienature.fct_get_nomenclature_type('RAIN'), '1', 'NO_RAIN', 'Absente')
      , (pr_vigienature.fct_get_nomenclature_type('RAIN'), '2', 'SMALL_RAIN', 'Bruine')
      , (pr_vigienature.fct_get_nomenclature_type('RAIN'), '3', 'STRONG_RAIN', 'Averses')
      , (pr_vigienature.fct_get_nomenclature_type('WIND'), '1', 'NO_WIND', 'Absent')
      , (pr_vigienature.fct_get_nomenclature_type('CLOUD'), '2', 'TWO_THIRD', '33-66%')
      , (pr_vigienature.fct_get_nomenclature_type('CLOUD'), '1', 'ONE_THIRD', '0-33%')
      , (pr_vigienature.fct_get_nomenclature_type('CLOUD'), '3', 'THREE_THIRD', '66-100%')
      , (pr_vigienature.fct_get_nomenclature_type('WIND'), '3', 'MIDDLE_STRONG_WIND', 'Moyen à fort')
      , (pr_vigienature.fct_get_nomenclature_type('WIND'), '2', 'WEAK_WIND', 'Faible')
      , (pr_vigienature.fct_get_nomenclature_type('VISIBILITY'), '1', 'GOOD_VISIBILITY', 'Bonne')
      , (pr_vigienature.fct_get_nomenclature_type('VISIBILITY'), '3', 'BAD_VISIBILITY', 'Faible')
      , (pr_vigienature.fct_get_nomenclature_type('VISIBILITY'), '2', 'MODERATE_VISIBILITY', 'Modérée')
;